export const GET_ALL_FORCAST_REQUEST = "GET_ALL_FORCAST_REQUEST";
export const GET_ALL_FORCAST_SUCCESS = "GET_ALL_FORCAST_SUCCEED";
export const GET_ALL_FORCAST_FAIL = "GET_ALL_FORCAST_FAILIED";

export const ADD_FORCAST_REQUEST = "ADD_FORCAST_REQUEST";
export const ADD_FORCAST_SUCCESS = "ADD_FORCAST_SUCCEED";
export const ADD_FORCAST_RESET = "ADD_FORCAST_RESET";
export const ADD_FORCAST_FAIL = "ADD_FORCAST_FAILED";

export const EDIT_FORCAST_REQUEST = "EDIT_FORCAST_REQUEST";
export const EDIT_FORCAST_SUCCESS = "EDIT_FORCAST_SUCCESS";
export const EDIT_FORCAST_RESET = "EDIT_FORCAST_RESET";
export const EDIT_FORCAST_FAIL = "ADD_FORCASEDIT_FORCAST_FAILT_FAILED";

export const DELETE_FORCAST_REQUEST = "DELETE_FORCAST_REQUEST";
export const DELETE_FORCAST_SUCCESS = "DELETE_FORCAST_SUCCESS";
export const DELETE_FORCAST_RESET = "DELETE_FORCAST_RESET";
export const DELETE_FORCAST_FAIL = "DELETE_FORCAST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
